# Generated by Django 6.0.6 on 2026-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Loyiha havolasi')),
            ],
        ),
    ]
